#define IDQUIT        0x0003
#define IDDONE        0x0005

#define INPUTDLG      0x1000
#define ABOUT         0x1001
#define TITLE         0x1002
#define CALIBADD      0x1003
#define CALIBINS      0x1004
#define CALIBVIEW     0x1005
#define MINMAX        0x1006
#define SAMESCALE     0x1007
#define TRANSFER9350  0x1008
#define VISUAREA      0x1009
#define EXPCONDITION  0x100a
#define INSERTCTEXT   0x100b
#define CTEXTLIST     0x100c
#define CALIBLIST     0x100d
#define BKSUBTRACT    0x100e
#define SPECTRUMSUM   0x100f
#define INPUTCTEXT    0x1010
#define GPIBCONNECT   0x1011
#define PLOTOPTION    0x1012
#define COUNT         0x1013
#define CANCELDLG     0x1014

#define ID_I_PROMPT   0x0101
#define ID_I_TEXT     0x0102

#define ID_TITLE      0x0101
#define ID_XUNIT      0x0102
#define ID_YUNIT      0x0103

#define ID_MASS       0x0100
#define ID_CALIBNUM   0x0101
#define ID_TIME       0x0102

#define ID_ELEMENT    0x0100

#define ID_A          0x0101
#define ID_B          0x0102
#define ID_C          0x0103

#define ID_MIN        0x0101
#define ID_MAX        0x0102
#define ID_MINTITLE   0x0103
#define ID_MAXTITLE   0x0104
#define ID_OPTION     0x0105

#define ID_MEM0 0x0110
#define ID_MEM1 0x0111
#define ID_MEM2 0x0112
#define ID_MEM3 0x0113
#define ID_MEM4 0x0114
#define ID_MEM5 0x0115
#define ID_MEM6 0x0116
#define ID_MEM7 0x0117
#define ID_MEM8 0x0118
#define ID_MEM9 0x0119
#define ID_MEMA 0x011a
#define ID_MEMB 0x011b

#define ID_SELEMENT  0x0100
#define ID_SFOUR     0x0101
#define ID_SCOUV     0x0102
#define ID_SHe       0x0103
#define ID_SAr       0x0104
#define ID_SOTHER    0x0105
#define ID_ITYPE     0x0201
#define ID_IENERGY   0x0202
#define ID_ICOMMENT  0x0203
#define ID_ITYPE1    0x0701
#define ID_IENERGY1  0x0702
#define ID_ICOMMENT1 0x0703
#define ID_APLATE1   0x0301
#define ID_APLATE2   0x0302
#define ID_APLATE3   0x0303
#define ID_LENS1     0x0401
#define ID_LENS2     0x0402
#define ID_REFV1     0x0501
#define ID_REFV2     0x0502
#define ID_REFV3     0x0503
#define ID_RANGLE    0x0504
#define ID_RCOMMENT  0x0505
#define ID_CHICANE1  0x0601
#define ID_CHICANE2  0x0602
#define ID_COMMENT1  0x0701
#define ID_COMMENT2  0x0702
#define ID_COMMENT3  0x0703

#define ID_CALCUL 0x0100

#define ID_TOF    0x0101
#define ID_CTEXT  0x0102 

#define IDCLOSE     0x1110
#define IDPRINT     0x1111
#define IDSAVE      0x1112
#define IDDELETE    0x1113

#define ID_CTEXTLIST 0x0101
#define ID_TIME      0x0102
#define ID_EDITCTEXT 0x0103
#define ID_MODIFY    0x0104
#define ID_DELETE    0x0105

#define ID_CALIBLIST 0x0101
#define ID_PRINT     0x0201

#define ID_EQ1       0x0201
#define ID_EQ2       0x0202
#define ID_EQ3       0x0203

#define ID_a0  0x0300
#define ID_a1  0x0301
#define ID_a2  0x0302
#define ID_a3  0x0303
#define ID_a4  0x0304
#define ID_a5  0x0305

#define ID_GROUP1  0x1001
#define ID_GROUP2  0x1002
#define ID_GROUP3  0x1003
#define ID_GROUP4  0x1004
#define ID_GROUP5  0x1005

#define ID_NPOINT  0x0300

#define ID_BRDNAME 0x0101
#define ID_DEVNAME 0x0102
#define ID_DEVAD   0x0103

#define ID_NTOT      0x0101
#define ID_NSEG      0x0103
#define ID_THRESHOLD 0x0104

#define ID_TEXT 0x0101
#define ID_DONE 0x0102

